#!/bin/bash

export PROJECTDIR="$(pwd)"
export OUTPUTDIR="${PROJECTDIR}/build"
export OUTPUTLIBDIR="${OUTPUTDIR}/lib"

export MAKEFILEDIR="${PROJECTDIR}/makefiles"
export PREFIX_INC="${PROJECTDIR}/includes"
export PREFIX_LIB="${OUTPUTLIBDIR}"

export BINNAME="run"

export LD_LIBRARY_PATH="${OUTPUTLIBDIR}":"${LD_LIBRARY_PATH}"

