#!/bin/bash

export PROJECTDIR="$(pwd)"
export MAKEFILEDIR="${PROJECTDIR}/makefiles"
export PREFIX_INC="${PROJECTDIR}/includes"
export PREFIX_LIB="./"

export OUTPUTDIR="${PROJECTDIR}/build"
export OUTPUTLIBDIR="${OUTPUTDIR}/parser"
