#!/bin/bash

export PROJECTDIR="$(pwd)"
export OUTPUTDIR="${PROJECTDIR}/build"
export OUTPUTLIBDIR="${OUTPUTDIR}/parser"

export MAKEFILEDIR="${PROJECTDIR}/makefiles"
export PREFIX_INC="${PROJECTDIR}/includes"
export PREFIX_LIB="${OUTPUTLIBDIR}"

export BINNAME="dcq"

